model = "gpt-5.1-codex-max"
model_reasoning_effort = "medium"
hide_agent_reasoning = true
network_access = true

web_search_request = true

[mcp_servers.context7]
command = "bunx"
args = ["@upstash/context7-mcp"]

[projects."/Users/kaoru/ghq/github.com/kkkaoru/keiba"]
trust_level = "trusted"

[projects."/Users/kaoru/dotfiles"]
trust_level = "trusted"

[projects."/Users/kaoru/ghq/github.com/kkkaoru/reverse-proxy"]
trust_level = "trusted"

[projects."/Users/kaoru"]
trust_level = "trusted"

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true
